### ISSUE TITLE
Jetty12: look deeper in JettyLogger class, not used.

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/appengine-java-standard#71] opened 2023-10-20 13:59 UTC
In package com.google.appengine.tools.development.jetty.ee10 and package com.google.appengine.tools.development.jetty , for the local runtime, we did not copy the JettlyLogger class defined in the jetty9.4 code base:
https://github.com/GoogleCloudPlatform/appengine-java-standard/blob/ee10-jetty/runtime/local_jetty9/src/main/java/com/google/appengine/tools/development/jetty9/JettyLogger.java

Why, not sure, but it is used via a property elsewhere in jett12 code area, and I guess this cannot work well, need to investigate more.
See usage in https://github.com/GoogleCloudPlatform/appengine-java-standard/blob/ee10-jetty/runtime/local_jetty12/src/main/java/com/google/appengine/tools/development/jetty/JettyContainerService.java#L130

**Comment by ludoch** [comment] 2023-10-20 14:02
For lachlan to investigate first.

**Comment by lachlan-roberts** [comment] 2023-10-27 06:26
The `org.eclipse.jetty.util.log.JavaUtilLog` class that this extends is not available since Jetty 10+.

I have started a branch https://github.com/GoogleCloudPlatform/appengine-java-standard/tree/jetty12-logging
which is using `org.slf4j:slf4j-jdk14` to bind slf4j to java util logging. 
But I will need to further test this branch to see if it is working as intended.

**Comment by lachlan-roberts** [comment] 2023-10-31 04:13
I tested the branch and it is working, so I have merged it into the `ee10-jetty` branch

the logs on the Google Cloud Log Explorer shows that the logs are now coming from `projects/jetty9-work/logs/%2Fvar%2Flog%2Fapp` and not `stderr`

**Comment by ludoch** [comment] 2023-11-02 17:16
https://github.com/GoogleCloudPlatform/appengine-java-standard/commit/648011409c0efd0bb21b3a5b73c46c7c1c9307d2

**Closed** 2023-11-02 17:15 UTC
